require("svnplug.patches.UserInterfaceModel")
require("svnplug.patches.GameController")
require("svnplug.patches.ScoreSystemContainer")
require("svnplug.patches.HitErrorView")
require("svnplug.patches.GameplayController")
require("svnplug.patches.osu_ui.MainMenu")
require("svnplug.patches.osu_ui.Scene")
